using State.@event;

namespace State.mapper
{
    public interface EventMapper
    {

        /**
         * Handles the mapping process
         * @param data The data of the event
         * @param event The Event generated by previous mapper, if any. Can be null
         * @param chain The chain of mappers
         */
        void doMap(EventData data, MapperChain chain);
    }
}