using System.Collections.Generic;
using State.@event;

namespace State.mapper
{
    public class MapperChain
    {

        private Queue<EventMapper> mappers;

        public MapperChain()
        {
            this.mappers = new LinkedListQueue<EventMapper>();
        }
        /**
         * Calls the next mapper in the chain, if any
         * @param data The data to pass along the chain
         * @param event the event generated by last {@link EventMapper}, if any 
         */
        public void doMap(EventData data)
        {
            if (this.mappers.peek() != null)
            {
                EventMapper mapper = this.mappers.poll();
                mapper.doMap(data, this);
            }
        }

        /**
         * @param applianceEventMapper
         */
        public void addToChain(EventMapper applianceEventMapper)
        {
            //Add this to a queue
            mappers.offer(applianceEventMapper);

        }

    }
}